spring:
  application:
    name: tlias_wed_management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

# mybatis顶格，和spring同一层级，前面无空格
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/leaning/mapper/*.xml
  type-aliases-package: com.leaning.pojo



aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: h-tlias-web-management
      region: cn-beijing